[package]
name = "bookmark_directories"
version = "0.0.3"
edition = "2021"
author = "Sha-dos"
repository = "https://github.com/Sha-dos/bookmark_directories"
description = "A small package for saving and loading directories in terminal"
license = "MIT"